// Code generated by counterfeiter. DO NOT EDIT.
package typesfakes

import (
	"context"
	"database/sql/driver"
	"sync"

	typesa "github.com/exasol/exasol-driver-go/pkg/types"
	"github.com/exasol/exasol-personal/internal/connect/exasol/types"
)

type FakeExasolConnector struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ExecStub        func(string, []driver.Value) (driver.Result, error)
	execMutex       sync.RWMutex
	execArgsForCall []struct {
		arg1 string
		arg2 []driver.Value
	}
	execReturns struct {
		result1 driver.Result
		result2 error
	}
	execReturnsOnCall map[int]struct {
		result1 driver.Result
		result2 error
	}
	SimpleExecStub        func(context.Context, string) (*typesa.SqlQueriesResponse, error)
	simpleExecMutex       sync.RWMutex
	simpleExecArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	simpleExecReturns struct {
		result1 *typesa.SqlQueriesResponse
		result2 error
	}
	simpleExecReturnsOnCall map[int]struct {
		result1 *typesa.SqlQueriesResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExasolConnector) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExasolConnector) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeExasolConnector) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeExasolConnector) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeExasolConnector) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeExasolConnector) Exec(arg1 string, arg2 []driver.Value) (driver.Result, error) {
	var arg2Copy []driver.Value
	if arg2 != nil {
		arg2Copy = make([]driver.Value, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.execMutex.Lock()
	ret, specificReturn := fake.execReturnsOnCall[len(fake.execArgsForCall)]
	fake.execArgsForCall = append(fake.execArgsForCall, struct {
		arg1 string
		arg2 []driver.Value
	}{arg1, arg2Copy})
	stub := fake.ExecStub
	fakeReturns := fake.execReturns
	fake.recordInvocation("Exec", []interface{}{arg1, arg2Copy})
	fake.execMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExasolConnector) ExecCallCount() int {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return len(fake.execArgsForCall)
}

func (fake *FakeExasolConnector) ExecCalls(stub func(string, []driver.Value) (driver.Result, error)) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = stub
}

func (fake *FakeExasolConnector) ExecArgsForCall(i int) (string, []driver.Value) {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	argsForCall := fake.execArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeExasolConnector) ExecReturns(result1 driver.Result, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	fake.execReturns = struct {
		result1 driver.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeExasolConnector) ExecReturnsOnCall(i int, result1 driver.Result, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	if fake.execReturnsOnCall == nil {
		fake.execReturnsOnCall = make(map[int]struct {
			result1 driver.Result
			result2 error
		})
	}
	fake.execReturnsOnCall[i] = struct {
		result1 driver.Result
		result2 error
	}{result1, result2}
}

func (fake *FakeExasolConnector) SimpleExec(arg1 context.Context, arg2 string) (*typesa.SqlQueriesResponse, error) {
	fake.simpleExecMutex.Lock()
	ret, specificReturn := fake.simpleExecReturnsOnCall[len(fake.simpleExecArgsForCall)]
	fake.simpleExecArgsForCall = append(fake.simpleExecArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.SimpleExecStub
	fakeReturns := fake.simpleExecReturns
	fake.recordInvocation("SimpleExec", []interface{}{arg1, arg2})
	fake.simpleExecMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExasolConnector) SimpleExecCallCount() int {
	fake.simpleExecMutex.RLock()
	defer fake.simpleExecMutex.RUnlock()
	return len(fake.simpleExecArgsForCall)
}

func (fake *FakeExasolConnector) SimpleExecCalls(stub func(context.Context, string) (*typesa.SqlQueriesResponse, error)) {
	fake.simpleExecMutex.Lock()
	defer fake.simpleExecMutex.Unlock()
	fake.SimpleExecStub = stub
}

func (fake *FakeExasolConnector) SimpleExecArgsForCall(i int) (context.Context, string) {
	fake.simpleExecMutex.RLock()
	defer fake.simpleExecMutex.RUnlock()
	argsForCall := fake.simpleExecArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeExasolConnector) SimpleExecReturns(result1 *typesa.SqlQueriesResponse, result2 error) {
	fake.simpleExecMutex.Lock()
	defer fake.simpleExecMutex.Unlock()
	fake.SimpleExecStub = nil
	fake.simpleExecReturns = struct {
		result1 *typesa.SqlQueriesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeExasolConnector) SimpleExecReturnsOnCall(i int, result1 *typesa.SqlQueriesResponse, result2 error) {
	fake.simpleExecMutex.Lock()
	defer fake.simpleExecMutex.Unlock()
	fake.SimpleExecStub = nil
	if fake.simpleExecReturnsOnCall == nil {
		fake.simpleExecReturnsOnCall = make(map[int]struct {
			result1 *typesa.SqlQueriesResponse
			result2 error
		})
	}
	fake.simpleExecReturnsOnCall[i] = struct {
		result1 *typesa.SqlQueriesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeExasolConnector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeExasolConnector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.ExasolConnector = new(FakeExasolConnector)
