// Copyright 2026 Exasol AG
// SPDX-License-Identifier: MIT

package runtimeadapter

import (
	"fmt"
	"strconv"

	"gopkg.in/yaml.v3"
)

const generatedManifestWarning = "# Generated by Exasol Personal. " +
	"Private runtime artifact; edits are discarded.\n"

type podManifest struct {
	APIVersion string      `yaml:"apiVersion"`
	Kind       string      `yaml:"kind"`
	Metadata   podMetadata `yaml:"metadata"`
	Spec       podSpec     `yaml:"spec"`
}

type podMetadata struct {
	Name        string            `yaml:"name"`
	Labels      map[string]string `yaml:"labels"`
	Annotations map[string]string `yaml:"annotations"`
}

type podSpec struct {
	RestartPolicy string         `yaml:"restartPolicy"`
	Containers    []podContainer `yaml:"containers"`
	Volumes       []podVolume    `yaml:"volumes"`
}

type podContainer struct {
	Name            string                   `yaml:"name"`
	Image           string                   `yaml:"image"`
	ImagePullPolicy string                   `yaml:"imagePullPolicy"`
	Args            []string                 `yaml:"args,omitempty"`
	Env             []podEnvironmentVariable `yaml:"env,omitempty"`
	Ports           []podPort                `yaml:"ports"`
	VolumeMounts    []podVolumeMount         `yaml:"volumeMounts"`
	SecurityContext podSecurityContext       `yaml:"securityContext"`
}

type podEnvironmentVariable struct {
	Name  string `yaml:"name"`
	Value string `yaml:"value"`
}

type podPort struct {
	Name          string `yaml:"name"`
	Protocol      string `yaml:"protocol"`
	ContainerPort int    `yaml:"containerPort"`
	HostPort      int    `yaml:"hostPort"`
	//nolint:tagliatelle // hostIP is the Kubernetes API field name.
	HostIP string `yaml:"hostIP"`
}

type podVolumeMount struct {
	Name      string `yaml:"name"`
	MountPath string `yaml:"mountPath"`
	ReadOnly  bool   `yaml:"readOnly,omitempty"`
}

type podSecurityContext struct {
	ProcMount string `yaml:"procMount"`
}

type podVolume struct {
	Name     string             `yaml:"name"`
	HostPath *podHostPathVolume `yaml:"hostPath,omitempty"`
	EmptyDir *podEmptyDirVolume `yaml:"emptyDir,omitempty"`
	Image    *podImageVolume    `yaml:"image,omitempty"`
}

type podHostPathVolume struct {
	Path string `yaml:"path"`
	Type string `yaml:"type"`
}

type podEmptyDirVolume struct {
	Medium    string `yaml:"medium"`
	SizeLimit string `yaml:"sizeLimit"`
}

type podImageVolume struct {
	Reference  string `yaml:"reference"`
	PullPolicy string `yaml:"pullPolicy"`
}

func RenderKubeManifest(spec WorkloadSpec) ([]byte, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}

	workloadName := WorkloadName(spec.DeploymentID)
	containerName := "db"
	hostAddress := spec.DBHostAddress
	if hostAddress == "" {
		hostAddress = "127.0.0.1"
	}
	manifest := podManifest{
		APIVersion: "v1",
		Kind:       "Pod",
		Metadata: podMetadata{
			Name: workloadName,
			Labels: map[string]string{
				"app.kubernetes.io/name":       "exasol-personal",
				"app.kubernetes.io/instance":   workloadName,
				"exasol.com/deployment-id":     spec.DeploymentID,
				"exasol.com/runtime-generated": "true",
			},
			Annotations: map[string]string{
				"io.podman.annotations.infra.name": workloadName + "-infra",
				"io.podman.annotations.pids-limit/" + containerName: strconv.Itoa(
					spec.Security.PIDsLimit,
				),
			},
		},
		Spec: podSpec{
			RestartPolicy: "Always",
			Containers: []podContainer{{
				Name:            containerName,
				Image:           spec.ImageReference,
				ImagePullPolicy: "Never",
				Args:            renderNanoArguments(spec),
				Env:             renderVersionCheckEnvironment(spec.VersionCheck),
				Ports: []podPort{{
					Name:          "database",
					Protocol:      "TCP",
					ContainerPort: NanoContainerPort,
					HostPort:      spec.DBHostPort,
					HostIP:        hostAddress,
				}},
				VolumeMounts: []podVolumeMount{
					{Name: "exa-data", MountPath: "/exa"},
					{Name: "shared-memory", MountPath: "/dev/shm"},
				},
				SecurityContext: podSecurityContext{ProcMount: "Unmasked"},
			}},
			Volumes: []podVolume{
				{
					Name: "exa-data",
					HostPath: &podHostPathVolume{
						Path: spec.DataPath,
						Type: "DirectoryOrCreate",
					},
				},
				{
					Name: "shared-memory",
					EmptyDir: &podEmptyDirVolume{
						Medium:    "Memory",
						SizeLimit: fmt.Sprintf("%dMi", spec.Security.ShmMiB),
					},
				},
			},
		},
	}

	for index, mount := range spec.SLCMounts {
		name := fmt.Sprintf("slc-%d", index)
		manifest.Spec.Volumes = append(manifest.Spec.Volumes, podVolume{
			Name: name,
			Image: &podImageVolume{
				Reference:  mount.Image,
				PullPolicy: "Never",
			},
		})
		manifest.Spec.Containers[0].VolumeMounts = append(
			manifest.Spec.Containers[0].VolumeMounts,
			podVolumeMount{Name: name, MountPath: mount.Target, ReadOnly: true},
		)
	}

	encoded, err := yaml.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("failed to encode Podman Kube manifest: %w", err)
	}

	return append([]byte(generatedManifestWarning), encoded...), nil
}

func renderNanoArguments(spec WorkloadSpec) []string {
	var arguments []string
	arguments = append(arguments, "init")
	arguments = append(arguments, spec.NanoArguments...)
	enabled := "0"
	if spec.VersionCheck.Enabled {
		enabled = "1"
	}
	arguments = append(arguments, "VERSION_CHECK_ENABLED="+enabled)
	if spec.VersionCheck.Enabled {
		arguments = append(
			arguments,
			"VERSION_CHECK_ENDPOINT="+spec.VersionCheck.URL,
			"VERSION_CHECK_INTERVAL_SEC="+strconv.Itoa(spec.VersionCheck.IntervalSeconds),
			"VERSION_CHECK_RETRY_INTERVAL_SEC="+strconv.Itoa(
				spec.VersionCheck.RetryIntervalSeconds,
			),
		)
		if spec.VersionCheck.OperatingSystem != "" {
			arguments = append(
				arguments,
				"VERSION_CHECK_OPERATING_SYSTEM="+spec.VersionCheck.OperatingSystem,
			)
		}
	}

	return arguments
}

func renderVersionCheckEnvironment(settings VersionCheckSettings) []podEnvironmentVariable {
	if !settings.Enabled {
		return nil
	}

	return []podEnvironmentVariable{{
		Name:  "VERSION_CHECK_IDENTITY",
		Value: settings.Identity,
	}}
}
