version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 28

    groups:
      actions-versions-updates:
        patterns:
          - "*"

    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
    cooldown:
      semver-patch-days: 21
      semver-minor-days: 28
    groups:
      python-weekly-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
    cooldown:
      semver-patch-days: 21
      semver-minor-days: 28
    groups:
      go-weekly-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    open-pull-requests-limit: 10
