sonar.projectKey=com.exasol:exasol-personal
sonar.organization=exasol
sonar.sources=.
sonar.exclusions=**/*_test.go,**/*_mocks.go,tests/**/*.py
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*_mocks.go,tests/**/*.py
sonar.go.coverage.reportPaths=./coverage-unit.out,./coverage-integration-linux/coverage-integration.out,./coverage-integration-windows/coverage-integration.out
sonar.coverage.exclusions=**/*_test.go,tests/**/*.py,tools/**,**/typesfakes/**
