// Code generated by counterfeiter. DO NOT EDIT.
package typesfakes

import (
	"sync"

	"github.com/exasol/exasol-personal/internal/connect/types"
)

type FakeLineReader struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ReadlineStub        func() (string, error)
	readlineMutex       sync.RWMutex
	readlineArgsForCall []struct {
	}
	readlineReturns struct {
		result1 string
		result2 error
	}
	readlineReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLineReader) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeLineReader) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeLineReader) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeLineReader) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLineReader) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLineReader) Readline() (string, error) {
	fake.readlineMutex.Lock()
	ret, specificReturn := fake.readlineReturnsOnCall[len(fake.readlineArgsForCall)]
	fake.readlineArgsForCall = append(fake.readlineArgsForCall, struct {
	}{})
	stub := fake.ReadlineStub
	fakeReturns := fake.readlineReturns
	fake.recordInvocation("Readline", []interface{}{})
	fake.readlineMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLineReader) ReadlineCallCount() int {
	fake.readlineMutex.RLock()
	defer fake.readlineMutex.RUnlock()
	return len(fake.readlineArgsForCall)
}

func (fake *FakeLineReader) ReadlineCalls(stub func() (string, error)) {
	fake.readlineMutex.Lock()
	defer fake.readlineMutex.Unlock()
	fake.ReadlineStub = stub
}

func (fake *FakeLineReader) ReadlineReturns(result1 string, result2 error) {
	fake.readlineMutex.Lock()
	defer fake.readlineMutex.Unlock()
	fake.ReadlineStub = nil
	fake.readlineReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeLineReader) ReadlineReturnsOnCall(i int, result1 string, result2 error) {
	fake.readlineMutex.Lock()
	defer fake.readlineMutex.Unlock()
	fake.ReadlineStub = nil
	if fake.readlineReturnsOnCall == nil {
		fake.readlineReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.readlineReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeLineReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLineReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.LineReader = new(FakeLineReader)
