# Github utilities
version: '3'

tasks:
  trigger-deployment-tests:
    desc: Trigger the deployment tests workflow on the current pushed commit (`task run-deployment-tests SUITE=local`, `task run-deployment-tests OS=macos-latest`)
    vars:
      OS: '{{default "all" .OS}}'
      SUITE: '{{default "all" .SUITE}}'
    cmds:
      - .github/scripts/run-deployment-tests.sh "{{.OS}}" "{{.SUITE}}"

  trigger-integration-tests:
    desc: Trigger the integration tests workflow on the current pushed commit (`task github:trigger-integration-tests OS=ubuntu-latest`)
    vars:
      OS: '{{default "all" .OS}}'
    cmds:
      - .github/scripts/run-integration-tests.sh "{{.OS}}"