package main

import (
	"bytes"
	"go/format"
	"maps"
	"os"
	"slices"
	"strings"
	"text/template"
)

const template_container = `
// Copyright 2026 Exasol AG
// SPDX-License-Identifier: MIT

// Code generated by localworkload generate. DO NOT EDIT

//go:build ( {{anyPlatforms .HostPlatforms}} )

package localworkloadbin

import _ "embed"

//go:embed generated/{{ .ContainerPlatform.OS }}/{{ .ContainerPlatform.Architecture }}/exasol-nano.tar.gz
var imageArchive []byte

//go:embed generated/{{ .ContainerPlatform.OS }}/{{ .ContainerPlatform.Architecture }}/image.json
var metadataJSON []byte

const Available = true
`

const template_unsupported = `
// Copyright 2026 Exasol AG
// SPDX-License-Identifier: MIT

// Code generated by localworkload generate. DO NOT EDIT

//go:build ! ( {{anyPlatforms .}} )

package localworkloadbin

var (
	imageArchive []byte
	metadataJSON []byte
)

const Available = false
`

func generate() error {
	anyPlatforms := func(platforms []ociPlatform) string {
		brace := func(s string) string {
			return " ( " + s + " ) "
		}
		platformConditions := []string{}
		for _, platform := range platforms {
			platformConditions = append(platformConditions, brace(platform.OS+" && "+platform.Architecture))
		}
		slices.Sort(platformConditions)
		return brace(strings.Join(platformConditions, " || "))
	}
	funcs := template.FuncMap{"anyPlatforms": anyPlatforms}
	pins, err := localImagePins(nil)
	if err != nil {
		return err
	}

	hostPlatforms := map[ociPlatform]struct{}{}

	for pinName, pin := range pins {
		f, err := os.Create("localworkloadbin_" + pinName + ".go")
		if err != nil {
			return err
		}
		defer f.Close()

		tmpl, err := template.New(pinName).Funcs(funcs).Parse(template_container)
		if err != nil {
			return err
		}

		var buf bytes.Buffer
		err = tmpl.Execute(&buf, pin)
		if err != nil {
			return err
		}
		src, err := format.Source(buf.Bytes())
		if err != nil {
			return err
		}
		f.Write(src)

		for _, platform := range pin.HostPlatforms {
			hostPlatforms[platform] = struct{}{}
		}
	}
	f, err := os.Create("localworkloadbin_unsupported.go")
	if err != nil {
		return err
	}
	defer f.Close()

	tmpl, err := template.New("unsupported").Funcs(funcs).Parse(template_unsupported)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, slices.Collect(maps.Keys(hostPlatforms)))
	if err != nil {
		return err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	f.Write(src)

	return nil
}
