name: tests-integration
description: Run Integration Tests
runs:
  using: "composite"
  steps:
    - name: Setup Python and Task
      uses: ./.github/actions/setup-python
    - name: Run Integration Tests
      shell: bash
      run: task tests-integration
