name: setup-task
description: Install Task build tool

inputs:
  version:
    description: Task version to install.
    required: false
    default: 3.44.1

runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2.1.0
      with:
        version: ${{ inputs.version }}
