name: setup-task
description: Install Task build tool

inputs:
  version:
    description: Task version to install.
    required: false
    default: 3.44.1

runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: go-task/setup-task@0ab1b2a65bc55236a3bc64cde78f80e20e8885c2 # v1
      with:
        version: ${{ inputs.version }}
