# Copyright 2026 Exasol AG
# SPDX-License-Identifier: MIT
# ruff: noqa: INP001

import argparse
import difflib
import json
import os
import subprocess
import sys
import tempfile
from collections.abc import Callable
from pathlib import Path

DOCS_ROOT = Path(__file__).resolve().parents[1]
BINARY = DOCS_ROOT.parent / "bin" / ("exasol.exe" if os.name == "nt" else "exasol")
OUTPUT = DOCS_ROOT / "content" / "cli-reference.md"
COMPLETION_COMMAND = "__complete"
COMPLETION_DIRECTIVE = ":"
SKIPPED_COMMANDS = frozenset({"help"})
PRESET_COMMANDS = ("install", "init")
PRESET_FLAG_SECTIONS = ("Infrastructure variable flags", "Installation variable flags")
GLOBAL_FLAGS_SECTION = "Global Flags:"
HELP_FLAG = "--help"
NAVIGATION_TRAILER = "for more information about a command."
COLLAPSED_SUBTREES = ("completion",)
HOME_PLACEHOLDER = "<home>"
INDENT = "    "
PREAMBLE = """<!-- Generated by scripts/cli_reference.py. Do not edit. -->

# CLI reference

Every command and option of the Exasol Launcher, taken from the launcher itself. Run
`exasol <command> --help` to see the same text locally.

Paths shown as `{placeholder}` refer to your home directory.

## Options available on every command

These options are accepted by `exasol` and by every subcommand, so they are listed here
instead of being repeated below.

```text
{global_flags}
```

`-h`, `--help` prints the help for the command it follows.
"""
GROUP_SUFFIX = "Commands:"
GLOBAL_FLAGS_ERROR = (
    "the launcher reports more than one set of global flags, so they cannot be "
    "documented once for every command"
)
UNGROUPED_ERROR = (
    "the launcher lists commands that no command group contains, so they would be "
    "missing from the reference: {names}"
)
PRESET_INTRO = (
    "`{command}` also accepts the variables of the selected preset. "
    "Each preset below adds these flags to the ones listed above."
)
DRIFT_ERROR = (
    "the committed CLI reference does not match the launcher binary; "
    "run 'task docs-cli-reference' and commit the result"
)
MISSING_BINARY_ERROR = "launcher binary not found: {binary}"
MISSING_REFERENCE_ERROR = "CLI reference not found: {output}"


class CliReferenceError(Exception):
    pass


def run(binary: Path, home: Path, *args: str) -> str:
    environment = dict(os.environ)
    # The launcher interpolates the home directory into its help text and resolves
    # presets below it. A writable directory is required: preset-specific flags are
    # silently omitted when the home directory does not exist.
    environment["HOME"] = str(home)
    environment["USERPROFILE"] = str(home)
    completed = subprocess.run(
        [str(binary), *args],
        check=True,
        capture_output=True,
        text=True,
        env=environment,
    )
    return completed.stdout


def normalize(text: str, home: Path) -> str:
    return text.replace(str(home), HOME_PLACEHOLDER).rstrip()


def subcommands(binary: Path, home: Path, path: tuple[str, ...]) -> list[str]:
    completion = run(binary, home, COMPLETION_COMMAND, *path, "")
    names = []
    for line in completion.splitlines():
        if line.startswith(COMPLETION_DIRECTIVE):
            continue
        name = line.partition("\t")[0].strip()
        if name and name not in SKIPPED_COMMANDS:
            names.append(name)
    return names


def walk(binary: Path, home: Path, path: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    discovered = [path]
    for name in subcommands(binary, home, path):
        discovered.extend(walk(binary, home, (*path, name)))
    return discovered


def infrastructure_presets(binary: Path, home: Path) -> list[str]:
    catalog = json.loads(run(binary, home, "presets", "list", "--json"))
    return [entry["id"] for entry in catalog["infrastructures"]]


def is_section_header(line: str) -> bool:
    return bool(line) and not line[0].isspace() and line.rstrip().endswith(":")


def sections(help_text: str) -> list[tuple[str, list[str]]]:
    # The leading description carries an empty header so it survives filtering.
    grouped: list[tuple[str, list[str]]] = [("", [])]
    for line in help_text.splitlines():
        if is_section_header(line):
            grouped.append((line, []))
        grouped[-1][1].append(line)
    return grouped


def select(help_text: str, matches: Callable[[str], bool]) -> str:
    kept = (
        "\n".join(lines).strip("\n")
        for header, lines in sections(help_text)
        if matches(header)
    )
    return "\n\n".join(body for body in kept if body)


def global_flags(help_text: str) -> str:
    # The per-command --help line is the only part that varies, so it is dropped here
    # and described once in the preamble instead.
    selected = select(help_text, lambda header: header == GLOBAL_FLAGS_SECTION)
    lines = selected.splitlines()[1:]
    return "\n".join(line for line in lines if HELP_FLAG not in line).strip("\n")


def strip_repeated(help_text: str) -> str:
    selected = select(help_text, lambda header: header != GLOBAL_FLAGS_SECTION)
    return "\n".join(
        line for line in selected.splitlines() if NAVIGATION_TRAILER not in line
    ).strip("\n")


def preset_flags(help_text: str) -> str:
    # Preset variables are the only part of the help that changes per preset, so the
    # rest of the command's help is not repeated for every preset.
    return select(help_text, lambda header: header.startswith(PRESET_FLAG_SECTIONS))


def command_groups(root_help: str) -> list[tuple[str, list[str]]]:
    # The launcher already groups its commands for `exasol --help`; reusing that keeps
    # the reference in the product's own order instead of inventing one here.
    groups = []
    for header, lines in sections(root_help):
        if not header.endswith(GROUP_SUFFIX):
            continue
        names = [
            stripped.split()[0]
            for line in lines[1:]
            if (stripped := line.strip()) and line.startswith("\t")
        ]
        groups.append((header.removesuffix(":"), names))
    return groups


def block(heading: str, command: str, body: str, label: str) -> str:
    attributes = f' {{ data-toc-label="{label}" }}' if label else ""
    return f"{heading} `{command}`{attributes}\n\n```text\n{body}\n```\n"


def collapsed_block(command: str, body: str) -> str:
    fenced = f"```text\n{body}\n```"
    indented = "\n".join(
        INDENT + line if line else line for line in fenced.splitlines()
    )
    return f'??? note "`{command}`"\n\n{indented}\n'


def is_collapsed(path: tuple[str, ...]) -> bool:
    return len(path) > 1 and path[0] in COLLAPSED_SUBTREES


def command_help(binary: Path, home: Path, path: tuple[str, ...]) -> str:
    return strip_repeated(normalize(run(binary, home, *path, "--help"), home))


def toc_label(path: tuple[str, ...]) -> str:
    # The command path is already in the heading; repeating "exasol" down the whole
    # table of contents just makes every entry harder to tell apart.
    return " ".join(path) if path else "exasol"


def help_section(binary: Path, home: Path, path: tuple[str, ...], depth: int) -> str:
    command = " ".join(("exasol", *path))
    body = command_help(binary, home, path)
    if is_collapsed(path):
        return collapsed_block(command, body)
    return block("#" * depth, command, body, toc_label(path))


def preset_section(
    binary: Path, home: Path, path: tuple[str, ...], depth: int
) -> str | None:
    body = preset_flags(normalize(run(binary, home, *path, "--help"), home))
    if not body:
        return None
    return block("#" * depth, " ".join(("exasol", *path)), body, path[-1])


def resolve_global_flags(binary: Path, home: Path, paths: list[tuple[str, ...]]) -> str:
    # Documenting these once is only honest while every command reports the same set.
    reported = {
        flags
        for path in paths
        if (flags := global_flags(normalize(run(binary, home, *path, "--help"), home)))
    }
    if len(reported) != 1:
        raise CliReferenceError(GLOBAL_FLAGS_ERROR)
    return reported.pop()


def command_sections(
    binary: Path, home: Path, paths: list[tuple[str, ...]], presets: list[str]
) -> list[str]:
    rendered = []
    for path in paths:
        depth = len(path) + 2
        rendered.append(help_section(binary, home, path, depth))
        if len(path) != 1 or path[0] not in PRESET_COMMANDS:
            continue
        variants = [
            variant
            for preset in presets
            if (variant := preset_section(binary, home, (*path, preset), depth + 1))
        ]
        if variants:
            command = " ".join(("exasol", *path))
            rendered.append(PRESET_INTRO.format(command=command) + "\n")
            rendered.extend(variants)
    return rendered


def render(binary: Path, home: Path) -> str:
    presets = infrastructure_presets(binary, home)
    paths = walk(binary, home)
    groups = command_groups(normalize(run(binary, home, "--help"), home))
    grouped = {name for _, names in groups for name in names}
    ungrouped = sorted({path[0] for path in paths if path} - grouped)
    if ungrouped:
        raise CliReferenceError(UNGROUPED_ERROR.format(names=", ".join(ungrouped)))

    page = [
        PREAMBLE.format(
            placeholder=HOME_PLACEHOLDER,
            global_flags=resolve_global_flags(binary, home, paths),
        ),
        *command_sections(binary, home, [()], presets),
    ]
    for title, names in groups:
        page.append(f"## {title}\n")
        for name in names:
            selected = [path for path in paths if path and path[0] == name]
            page.extend(command_sections(binary, home, selected, presets))
    return "\n".join(page).rstrip() + "\n"


def generate(binary: Path) -> str:
    if not binary.exists():
        raise CliReferenceError(MISSING_BINARY_ERROR.format(binary=binary))
    with tempfile.TemporaryDirectory() as home:
        return render(binary, Path(home))


def write(binary: Path, output: Path) -> None:
    output.write_text(generate(binary), encoding="utf-8")


def check(binary: Path, output: Path) -> None:
    if not output.exists():
        raise CliReferenceError(MISSING_REFERENCE_ERROR.format(output=output))
    expected = generate(binary)
    committed = output.read_text(encoding="utf-8")
    if committed == expected:
        return
    diff = difflib.unified_diff(
        committed.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{output} (committed)",
        tofile=f"{output} (launcher)",
    )
    sys.stderr.writelines(diff)
    raise CliReferenceError(DRIFT_ERROR)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the CLI reference from the launcher binary"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed reference instead of rewriting it",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        if args.check:
            check(BINARY, OUTPUT)
        else:
            write(BINARY, OUTPUT)
    except CliReferenceError as error:
        sys.stderr.write(f"error: {error}\n")
        return 1
    except subprocess.CalledProcessError as error:
        sys.stderr.write(f"error: {error}\n")
        return error.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
