name: tests-deployment
description: Run Deployment Tests
inputs:
  infra:
    description: Infrastructure preset for deployment tests.
    required: false
    default: aws
  task:
    description: Taskfile target to execute for deployment tests.
    required: false
    default: tests-deployment
runs:
  using: "composite"
  steps:
    - name: Setup Python and Task
      uses: ./.github/actions/setup-python
    - name: Run Deployment Tests
      shell: bash
      run: task ${{ inputs.task }} INFRA=${{ inputs.infra }}
