name: setup-aws
description: Setup AWS credentials
inputs:
  aws-ci-role:
    description: AWS role to use.
    required: true
  aws-region:
    description: AWS region to use.
    required: true
runs:
  using: "composite"
  steps:
    - name: Connect GitHub to AWS account
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
      with:
        role-to-assume: ${{ inputs.aws-ci-role }}
        role-session-name: aws-role-for-exasol-launcher
        aws-region: "${{ inputs.aws-region }}"
