// Copyright 2026 Exasol AG
// SPDX-License-Identifier: MIT

// Code generated by localworkload generate. DO NOT EDIT

//go:build !((darwin && arm64) || (linux && amd64) || (linux && arm64) || (windows && amd64))

package localworkloadbin

var (
	imageArchive []byte
	metadataJSON []byte
)

const Available = false
