// Copyright 2026 Exasol AG
// SPDX-License-Identifier: MIT

// Code generated by localworkload generate. DO NOT EDIT

//go:build (linux && amd64) || (windows && amd64)

package localworkloadbin

import _ "embed"

//go:embed generated/linux/amd64/exasol-nano.tar.gz
var imageArchive []byte

//go:embed generated/linux/amd64/image.json
var metadataJSON []byte

const Available = true
