// Copyright 2026 Exasol AG
// SPDX-License-Identifier: MIT

// Code generated by localworkload generate. DO NOT EDIT

//go:build darwin && arm64

package localworkloadbin

import _ "embed"

//go:embed generated/linux/arm64/exasol-nano.tar.gz
var imageArchive []byte

//go:embed generated/linux/arm64/image.json
var metadataJSON []byte

const Available = true
