version: '3'

vars:
  COMMAND_NAME: exasol-cleanup
  BINARY_SUFFIX:
    sh: test "$(go env GOOS)" = "windows" && echo ".exe" || true
  BUILD_DIR_NAME: "bin"

tasks:
  default:
    silent: true
    cmds:
      - "task --list"

  build:
    desc: Build the cleanup binary
    cmds:
      - |
        go build -o {{.BUILD_DIR_NAME}}/{{.COMMAND_NAME}}{{.BINARY_SUFFIX}} ./cmd/cleanup

  tests-unit:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  lint-golang:
    desc: Run golangci-lint linters
    cmds:
      - go tool golangci-lint run ./...

  lint-golang-fix:
    desc: Run golangci-lint linters and apply automatic fixes
    cmds:
      - go tool golangci-lint run ./... --fix

  lint:
    desc: Run all linters
    cmds:
      - task: lint-golang

  fmt:
    desc: Format Go code
    cmds:
      - task: lint-golang-fix

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR_NAME}}
