name: Exasol on Hetzner Cloud with Ubuntu
description: Provisioning on Hetzner Cloud. Ubuntu, block storage data volume, public IPs.

tofu:
  variablesFile: variables_public.tf
  varsOutputFile: vars.tfvars

powerControl:
  provider: hetzner
