# Extra jobs to run on merges to main.
# Specifically, build the binaries for the other platforms we want support
name: Main branch pushed - Build Windows and MacOS

on:
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          # this is need because we use "git describe" to get the latest version from git       
          fetch-depth: 0
      - uses: ./.github/actions/build

      - name: Upload file
        if: ${{ !contains(matrix.os, 'windows') }}
        uses: actions/upload-artifact@v7
        with:
          name: exasol-${{ matrix.os }}
          path: bin/exasol

      - name: Upload file (Windows)
        if: ${{ contains(matrix.os, 'windows') }}
        uses: actions/upload-artifact@v7
        with:
          name: exasol-${{ matrix.os }}
          path: bin/exasol.exe
